### PR TITLE
Reconnect console after container restart

### LINKED ISSUE #1089: Container console doesn't reconnect after restarting a container
Cockpit version: 275
Cockpit-podman version: 52
Podman version: 4.2.0
OS: Fedora 36

Steps to reproduce

1. Open a container console
2. Restart the container
3. Console stays disconnected after container is restarted

### PR DESCRIPTION
**Pull request by skazi0**
During restart container's State is still "running" and console was getting disconnected but not reconnected. Additional flag was added to keep information about restart and connect channels again.

Closes #1089

### CODE REVIEW

File: src/app.jsx [hunk 1]
```diff
@@ -311,6 +311,9 @@ class Application extends React.Component {
                         reply = reply[0];
 
                         reply.isSystem = system;
+                        // HACK: during restart State never changes from "running"
```
Comment (marusak) [inline src/app.jsx:314]: if we would change this to:
```
+                        if (event.Action === "restart")
+                            reply.State = "restarting";
```
we don't need any additional changes and it will also update the label. We should then only define it in `src/utils.js` for it being localized.

WDYT?

Comment (skazi0) [reply src/app.jsx:314]: That was my first idea but it has some unwanted side effects. See: https://github.com/cockpit-project/cockpit-podman/issues/1089#issuecomment-1240676131

Comment (marusak) [reply src/app.jsx:314]: Ah right. So we switched by default to showing all containers and not only running ones, so this should not be a big deal. Also we could show restarting as running

Comment (skazi0) [reply src/app.jsx:314]: Hmmm. I think changing the filter to include "restarting" even when "only running" is selected might be a good/better solution.

Comment (skazi0) [reply src/app.jsx:314]: done

Comment (jelly) [reply src/app.jsx:314]: Please add the `restarting` translation to `src/utils.js` with a comment why it's explicitly added there.

Comment (kubat-david) [reply src/app.jsx:314]: Hi, the `restarting` translation has been added to `src/utils.js` by @skazi0

**Review by marusak — APPROVED** [review]
Thank you!

**Review by marusak — APPROVED** [review]
Thanks!
