### PR TITLE
Reply from REST can come in pieces

### LINKED ISSUE #1025: streaming podman metrics breaks with ~ 14 containers active
Cockpit-podman version: 0cb9c37d89b86c3ef29423f1845c55f581ce57ef
Podman version: 4.1.1

When having ~ 14 containers active I noticed the page was running slow and the console is full of errors.

The json we try to parse is streamed with `cockpit.http().request().stream()

```
    connection.monitor = function(options, callback, system, return_raw) {
        return new Promise((resolve, reject) => {
            http.request(options)
                    .stream(data => {
                        if (return_raw)
                            callback(data);
                        else
                            callback(JSON.parse(data));
                    })
                    .catch((error, content) => {
                        manage_error(reject, error, content);
                    })
```
The data we try to parse is not complete, is that a bug in cockpit.http or our podman implementation.

```
rest.js:31 SyntaxError: Unexpected token , in JSON at position 4
    at JSON.parse (<anonymous>)
    at Function.<anonymous> (rest.js:29:43)
    at C.<anonymous> (cockpit.js:1:42360)
    at C.o (cockpit.js:1:9635)
    at s (cockpit.js:1:603)
    at C.value (cockpit.js:1:2523)
    at f (cockpit.js:1:7995)
    at cockpit.js:1:6003
    at A.n.onmessage.e.dispatch_data [as onmessage] (cockpit.js:1:6008)
    at cockpit.js:1:3875 '2146,"NetInput":1032,"NetOutput":14708,"BlockInput":0,"BlockOutput":0,"PIDs":11,"UpTime":7132388000,"Duration":7132388000},{"AvgCPU":0,"ContainerID":"ffca12a441560efd349f2f2ed6bb83758b19076df112c5b559ee1c6fdecc9e38","Name":"aurweb-mariadb_init-1","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0}]}\n'
(anonymous) @ rest.js:31
(anonymous) @ cockpit.js:1
o @ cockpit.js:1
s @ cockpit.js:1
value @ cockpit.js:1
f @ cockpit.js:1
(anonymous) @ cockpit.js:1
A.n.onmessage.e.dispatch_data @ cockpit.js:1
(anonymous) @ cockpit.js:1
postMessage (async)
(anonymous) @ index.js:2
A.n.onmessage.e.dispatch_data @ cockpit.js:1
rest.js:31 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.<anonymous> (rest.js:29:43)
    at C.<anonymous> (cockpit.js:1:42360)
    at C.o (cockpit.js:1:9635)
    at s (cockpit.js:1:603)
    at C.value (cockpit.js:1:2523)
    at f (cockpit.js:1:7995)
    at cockpit.js:1:6003
    at A.n.onmessage.e.dispatch_data [as onmessage] (cockpit.js:1:6008)
    at cockpit.js:1:3875 '{"Error":null,"Stats":[{"AvgCPU":0,"ContainerID":"0159222be10a0daf451469e7a828a253d1eb3a5d646f95f0fd56246033d5b6af","Name":"cockpit-metrics-prometheus","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0,"ContainerID":"069809969bcd5250c5937c60c360de6861e6c829b179ffe1316b6b6b45d6365f","Name":"fedorapackager","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0.5560038848855239,"ContainerID":"0d13853032ce0830239aea22abdc215f0be6244eb96d0275a234e53cc4e1cd24","Name":"aurweb-php-fpm-1","PerCPU":null,"CPU":0.39218455880889425,"CPUNano":7165927000,"CPUSystemNano":2308173,"SystemNano":1656402184078644963,"MemUsage":7270400,"MemLimit":33410396160,"MemPerc":0.021760891326108717,"NetInput":1032,"NetOutput":8820,"BlockInput":0,"BlockOutput":0,"PIDs":4,"UpTime":7165927000,"Duration":7165927000},{"AvgCPU":0,"ContainerID":"11d179ae526c894b2faae7cdda7a66204818948bdb3a8526393c3cf2e33133e4","Name":"869599f79e8a-infra","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0.356714133440765,"ContainerID":"14d941cd1327f62aaaa6ef5ede4a9eb58525affd473dcbfce3fecbf625c01dbc","Name":"aurweb-cgit-fastapi-1","PerCPU":null,"CPU":0.4037962553494008,"CPUNano":4597103000,"CPUSystemNano":2040367,"SystemNano":1656402184079120196,"MemUsage":1167360,"MemLimit":33410396160,"MemPerc":0.0034940022692625267,"NetInput":1032,"NetOutput":8528,"BlockInput":0,"BlockOutput":0,"PIDs":2,"UpTime":4597103000,"Duration":4597103000},{"AvgCPU":0.3993426873021814,"ContainerID":"2e14479529470f2858184ffe237276cab6f2029ac4896283c306c6e397430a2f","Name":"aurweb-smartgit-1","PerCPU":null,"CPU":0.4380028316949944,"CPUNano":5171564000,"CPUSystemNano":2173330,"SystemNano":1656402184079538690,"MemUsage":1171456,"MemLimit":33410396160,"MemPerc":0.0035062619263476584,"NetInput":1032,"NetOutput":11058,"BlockInput":0,"BlockOutput":0,"PIDs":2,"UpTime":5171564000,"Duration":5171564000},{"AvgCPU":0,"ContainerID":"30452c2ae7d3c4951eac922b2efb656be94bd44eb0268a4ecf73ab52385135bb","Name":"distracted_williams","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0,"ContainerID":"30e89768359b9c9d795ffe1336e4f90b70ff9a9ce70250c2992e910d4290d5ba","Name":"focused_torvalds","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0,"ContainerID":"3197f240dcdfddcd5e8d46b670134a8404432fa2e6c71f9076ecca8d559b1417","Name":"aurweb-aurweb-image-1","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0,"ContainerID":"350a54cdc78de9b88fe1d9041c9aecabd4339ec1289f3587dfc268c6266ba0f8","Name":"sweet_hodgkin","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":6.899214467732441,"ContainerID":"3c9725b64dc42c8552a3c0c205ca5912e8328c8ef608183e2ee0ef1ed0a5c251","Name":"aurweb-cron-1","PerCPU":null,"CPU":0.0007985063239718567,"CPUNano":89328543000,"CPUSystemNano":6182620,"SystemNano":1656402184080078294,"MemUsage":1093632,"MemLimit":33410396160,"MemPerc":0.0032733284417301566,"NetInput":167082,"NetOutput":9706365,"BlockInput":0,"BlockOutput":0,"PIDs":2,"UpTime":89328543000,"Duration":89328543000},{"AvgCPU":0,"ContainerID":"411646287c886ed29aee3dce7ff804cda9'
(anonymous) @ rest.js:31
(anonymous) @ cockpit.js:1
o @ cockpit.js:1
s @ cockpit.js:1
value @ cockpit.js:1
f @ cockpit.js:1
(anonymous) @ cockpit.js:1
A.n.onmessage.e.dispatch_data @ cockpit.js:1
(anonymous) @ cockpit.js:1
postMessage (async)
(anonymous) @ index.js:2
A.n.onmessage.e.dispatch_data @ cockpit.js:1
rest.js:31 SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.<anonymous> (rest.js:29:43)
    at C.<anonymous> (cockpit.js:1:42360)
    at C.o (cockpit.js:1:9635)
    at s (cockpit.js:1:603)
    at C.value (cockpit.js:1:2523)
    at f (cockpit.js:1:7995)
    at cockpit.js:1:6003
    at A.n.onmessage.e.dispatch_data [as onmessage] (cockpit.js:1:6008)
    at cockpit.js:1:3875 'a7db5ed3931ad16fd6759078445514","Name":"aurweb-nginx-1","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":8.409326239794057,"ContainerID":"42817b6517f2222e30041842b8148d765819e9aa352dab11e477be243f5902ce","Name":"aurweb-fastapi-1","PerCPU":null,"CPU":4.597553668344836,"CPUNano":108349573000,"CPUSystemNano":27863172,"SystemNano":1656402184080533886,"MemUsage":91873280,"MemLimit":33410396160,"MemPerc":0.2749841084195034,"NetInput":1032,"NetOutput":7604,"BlockInput":0,"BlockOutput":0,"PIDs":4,"UpTime":108349573000,"Duration":108349573000},{"AvgCPU":0.3514338242144361,"ContainerID":"46d6f0f9176998a89d21589bb28911967ec9e62c5164247e8447bb71d1c17fa7","Name":"aurweb-cgit-php-1","PerCPU":null,"CPU":0.35383095315170404,"CPUNano":4528034000,"CPUSystemNano":1968582,"SystemNano":1656402184080884264,"MemUsage":1167360,"MemLimit":33410396160,"MemPerc":0.0034940022692625267,"NetInput":1032,"NetOutput":8146,"BlockInput":0,"BlockOutput":0,"PIDs":2,"UpTime":4528034000,"Duration":4528034000},{"AvgCPU":0,"ContainerID":"47f4f466c5d3bd650198a3d86b863e358c18c9215156381ed39b94736c987fd8","Name":"loving_tesla","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0,"ContainerID":"4b062a3d5b718e8fa78de562c87cb97ebcd99eaf63298066e3cfe87845a5d5ad","Name":"wordpress-db","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0.5242652096119308,"ContainerID":"551eafd8b52fb486717f2f9524a22ebcae0c0589b3d97a6ad32d736c2a7ff00a","Name":"aurweb-redis-1","PerCPU":null,"CPU":0.4787347091224126,"CPUNano":6823559000,"CPUSystemNano":2983873,"SystemNano":1656402184081262974,"MemUsage":7503872,"MemLimit":33410396160,"MemPerc":0.02245969177996122,"NetInput":1032,"NetOutput":14326,"BlockInput":0,"BlockOutput":0,"PIDs":6,"UpTime":6823559000,"Duration":6823559000},{"AvgCPU":0,"ContainerID":"59b5439878e10d7af819ab8f2bede3a47c76909811d4e6d674056383facce505","Name":"9999","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0,"ContainerID":"6112827c094a86f55a8ab30fdffd8298b90c08d211db27486969fbaf39b80b3e","Name":"tasks","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0,"ContainerID":"6386b2d7ddb856e46d5e7447c6cbace9bd7f1e153be1eefa0a6c3d813e17d6fd","Name":"quirky_greider","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0,"ContainerID":"682c5f0be106d67a9573cda7bf46ad78467f3c80b164c7cfc86bde7c03900f36","Name":"cockpit-metrics-httpd","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0,"ContainerID":"6954ef24dc0f559fedad1eff83746cb0b8d37eb6b24f05f527e3750337ff8874","Name":"1ad77bf29144-infra","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0.6981935375069738,"ContainerID":"6cce78f836afbc94c0c51b3334c37a85918387726cc1e1dd9cf1eee13e6eeba9","Name":"aurweb-mariadb-1","PerCPU":null,"CPU":0.4750807079459276,"CPUNano":9086161000,"CPUSystemNano":3748185,"SystemNano":1656402184081765585,"MemUsage":197595136,"MemLimit":33410396160,"MemPerc":0.591418117443837,"'
(anonymous) @ rest.js:31
(anonymous) @ cockpit.js:1
o @ cockpit.js:1
s @ cockpit.js:1
value @ cockpit.js:1
f @ cockpit.js:1
(anonymous) @ cockpit.js:1
A.n.onmessage.e.dispatch_data @ cockpit.js:1
(anonymous) @ cockpit.js:1
postMessage (async)
(anonymous) @ index.js:2
A.n.onmessage.e.dispatch_data @ cockpit.js:1
rest.js:31 SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.<anonymous> (rest.js:29:43)
    at C.<anonymous> (cockpit.js:1:42360)
    at C.o (cockpit.js:1:9635)
    at s (cockpit.js:1:603)
    at C.value (cockpit.js:1:2523)
    at f (cockpit.js:1:7995)
    at cockpit.js:1:6003
    at A.n.onmessage.e.dispatch_data [as onmessage] (cockpit.js:1:6008)
    at cockpit.js:1:3875 'NetInput":1032,"NetOutput":13742,"BlockInput":0,"BlockOutput":0,"PIDs":14,"UpTime":9086161000,"Duration":9086161000},{"AvgCPU":0.21446402606912687,"ContainerID":"78be08d213b96e933320906e30ec2dc77f73586059c561340ee80abad6272485","Name":"fedora-toolbox-37","PerCPU":null,"CPU":0.03421509401455552,"CPUNano":186953746000,"CPUSystemNano":27029800,"SystemNano":1656402184081953993,"MemUsage":394940416,"MemLimit":33410396160,"MemPerc":1.182088395805481,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":260,"UpTime":186953746000,"Duration":186953746000},{"AvgCPU":0,"ContainerID":"8ffa7c57e52b27ff9ccfb6c6b38979e819845a48eb13a3fcf06dfabcc3b81dde","Name":"cockpit-metrics-grafana","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0.6001233263001446,"ContainerID":"b1df6fefcc1f1b8584e6d2f26e4cb562bbeb65b830b0de705b696460be41d0ab","Name":"aurweb-git-1","PerCPU":null,"CPU":0.42389428048777605,"CPUNano":7769501000,"CPUSystemNano":2514195,"SystemNano":1656402184082281861,"MemUsage":794624,"MemLimit":33410396160,"MemPerc":0.0023783734745155445,"NetInput":1032,"NetOutput":9912,"BlockInput":0,"BlockOutput":0,"PIDs":2,"UpTime":7769501000,"Duration":7769501000},{"AvgCPU":0,"ContainerID":"b297f8e928f931665f6f434f8128b2014fa25857c5c8e118f2899c17787b4689","Name":"fedora-toolbox-36","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0,"ContainerID":"cda3274c1143de2f759e275d4e06562f14aed55da9cf9a3c2ad0bba0ec7b4a77","Name":"peaceful_chaplygin","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0.73042385730821,"ContainerID":"dde945507e7810c15a662abd067ec232bb49c64ed0e3f09c3ce0b098ffab376c","Name":"aurweb-ca-1","PerCPU":null,"CPU":0.48060262714710944,"CPUNano":9502616000,"CPUSystemNano":4060705,"SystemNano":1656402184082658684,"MemUsage":19865600,"MemLimit":33410396160,"MemPerc":0.05945933686288861,"NetInput":1032,"NetOutput":13068,"BlockInput":0,"BlockOutput":0,"PIDs":14,"UpTime":9502616000,"Duration":9502616000},{"AvgCPU":0,"ContainerID":"e3cbbd1735cb44a2038d9012bb0831a4028d2436d5bb27ccf685cf044018fb05","Name":"wordpress-web","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0.41113267186138164,"ContainerID":"e57f6d4aec29b35769c78ad97173e4ad3ae3c9639ca2b02d19c03a1dc35f3785","Name":"aurweb-memcached-1","PerCPU":null,"CPU":0.3847591001047046,"CPUNano":5350739000,"CPUSystemNano":2244268,"SystemNano":1656402184083024054,"MemUsage":831488,"MemLimit":33410396160,"MemPerc":0.002488710388281729,"NetInput":1032,"NetOutput":14034,"BlockInput":0,"BlockOutput":0,"PIDs":11,"UpTime":5350739000,"Duration":5350739000},{"AvgCPU":0,"ContainerID":"ea5de013a155c5cd53dfb3b707def2c3c1d9c45ba8677fda8f6afd1fde44036d","Name":"distracted_darwin","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0,"ContainerID":"ec7bfdf4a08b9335a1bfdc1b4e141731c454bb1017beca0b10d8824bbcb6706f","Name":"quirky_chaum","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0},{"AvgCPU":0.5498256447011476,"ContainerID":"f379d4fcfe7c363a33df4efa58575f1e811dfaf1fdb9b4c5118f2d0eb575b5fe","Name":"aurweb-mariadb_test-1","PerCPU":null,"CPU":0.48266084721139135,"CPUNano":7156568000,"CPUSystemNano":2905035,"SystemNano":1656402184083440948,"MemUsage":176058368,"MemLimit":33410396160,"MemPe'
(anonymous) @ rest.js:31
(anonymous) @ cockpit.js:1
o @ cockpit.js:1
s @ cockpit.js:1
value @ cockpit.js:1
f @ cockpit.js:1
(anonymous) @ cockpit.js:1
A.n.onmessage.e.dispatch_data @ cockpit.js:1
(anonymous) @ cockpit.js:1
postMessage (async)
(anonymous) @ index.js:2
A.n.onmessage.e.dispatch_data @ cockpit.js:1
rest.js:31 SyntaxError: Unexpected token r in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.<anonymous> (rest.js:29:43)
    at C.<anonymous> (cockpit.js:1:42360)
    at C.o (cockpit.js:1:9635)
    at s (cockpit.js:1:603)
    at C.value (cockpit.js:1:2523)
    at f (cockpit.js:1:7995)
    at cockpit.js:1:6003
    at A.n.onmessage.e.dispatch_data [as onmessage] (cockpit.js:1:6008)
    at cockpit.js:1:3875 'rc":0.5269568404902146,"NetInput":1032,"NetOutput":14708,"BlockInput":0,"BlockOutput":0,"PIDs":11,"UpTime":7156568000,"Duration":7156568000},{"AvgCPU":0,"ContainerID":"ffca12a441560efd349f2f2ed6bb83758b19076df112c5b559ee1c6fdecc9e38","Name":"aurweb-mariadb_init-1","PerCPU":null,"CPU":0,"CPUNano":0,"CPUSystemNano":0,"SystemNano":0,"MemUsage":0,"MemLimit":0,"MemPerc":0,"NetInput":0,"NetOutput":0,"BlockInput":0,"BlockOutput":0,"PIDs":0,"UpTime":0,"Duration":0}]}\n'
(anonymous) @ rest.js:31
(anonymous) @ cockpit.js:1
```

### PR DESCRIPTION
**Pull request by marusak**
Maximum length on one message is 4096 characters. When the reply is
longer than that it will come in multiple messages. In such case we need to
connect them before trying to parse such message.
    
This for example happens when there are multiple containers and `Stats` often
are split into multiple messages.
    
Fixes #1025

### CODE REVIEW

**Comment by marusak** [comment]
```
RuntimeError: Timed out on 'set -eu
            systemctl stop podman.service podman.socket
            systemctl reset-failed podman.service podman.socket
            podman system reset --force
            killall -9 podman || true
            findmnt --list -otarget | grep /var/lib/containers/. | xargs -r umount
            '
```

Yeah, it takes somewhat longer to cleanup all 31 containers :man_shrugging: I will try to remove them outside of this cleanup

File: src/rest.js [hunk 1]
```diff
@@ -20,12 +20,23 @@ function connect(address, system) {
...
+                        else {
+                            buffer += data;
+
+                            try {
+                                const message = JSON.parse(buffer);
+                                buffer = "";
+                                callback(message);
+                            } catch {
+                                // Ignore, we already stored it is buffer
+                            }
```
Comment (martinpitt) [inline src/rest.js:38]: This is too brittle and probabilistic. Why not just let the bridge do the buffer assembly? I suggest using the original code, but as a .then() handler, instead of .stream(). We are not expecting huge replies here, and even if they were, the stream handler can't process individual chunks anyway -- so building up a buffer happens in any case. So let's just let cockpit.js do the job.

See https://cockpit-project.org/guide/latest/cockpit-http.html#cockpit-http-then

File: test/check-application [hunk 2]
```diff
@@ -2122,6 +2122,19 @@ class TestApplication(testlib.MachineCase):
...
         self.waitContainerRow(container_name_new)
 
+    def testMultipleContainers(self):
+        self.login()
+
+        # Create 31 containers
+        for i in range(31):
+            self.execute(True, f"podman run -dt --name container{i} quay.io/libpod/busybox:latest")
+
+        self.waitContainerRow("container30")
```
Comment (martinpitt) [inline test/check-application:2132]: So the race condition would have broken the protocol persistently? I.e. why does it only check for container30, but not for the 29 other ones?

File: test/check-application [hunk 3]
```diff
@@ -2122,6 +2122,19 @@ class TestApplication(testlib.MachineCase):
...
+
+        # Generic cleanup takes too long and timeouts, so remove these container manually one by one
+        for i in range(31):
+            self.execute(True, f"podman rm -f container{i}")
```
Comment (martinpitt) [inline test/check-application:2136]: `m.execute()` has a `timeout=` argument. I wonder if it's faster to do

    podman ps -aq --filter 'name=^container' | xargs podman rm -f

If not, then keep it like that.

**Review by martinpitt — CHANGES_REQUESTED** [review]
Thanks for spotting! Ugh, why did we use .stream() here in the first place..

File: src/rest.js (hunk 1 above)
Comment (marusak) [reply src/rest.js:38]: We handle `.then()` as well (each user of `.monitor()` declares it on they own), but it means that the monitor has closed. We use monitor for streaming of events as they happen - we open the connection and sit on it for the whole duration of session. And we just get messages on what has happened.

File: test/check-application (hunk 2 above)
Comment (marusak) [reply test/check-application:2132]: It will happen if the page is opened with more than ~15 containers as it get update for stats. I just put there wait for the last container to appear, that gives the page enough open time for the oops to appear. And the oops is what kills the test.

File: test/check-application (hunk 3 above)
Comment (marusak) [reply test/check-application:2136]: > podman ps -aq --filter 'name=^container' | xargs podman rm -f

that would also timeout. I could specify `timeout=` in `execute()` but would be kinda tricky to find the correct number that will not keep it stuck for too long if one container is stuck, yet is long enough for 30 containers.

File: test/check-application (hunk 2 above)
Comment (martinpitt) [reply test/check-application:2132]: I see, thanks!

File: src/rest.js (hunk 1 above)
Comment (martinpitt) [reply src/rest.js:38]: Ah, that's the monitor. So are we guaranteed to never get a chunk which includes the end of one JSON message and the start of another? Like this, if we'd get a first chunk like `{ a: "one", `, and a second one `"b": "two }\n{ "c": "three" }`, the first + second would either still be unparseable, or it would cut off and ignore the second object (as this resets `buffer`). If this is really getting a continuous stream of JSON blobs, then there must be *some* defined message separator? That's exactly what [jsonl](https://jsonlines.org/) is, after all. Then it could append new chunks to the buffer, check if the buffer contains `\n`, and if so, split it and process all parts but the last one (and keep that in the buffer).

Comment (marusak) [reply src/rest.js:38]: I believe it is guaranteed. We never saw that and the current behavior would be affected the same way as well.
The API does not try to send more messages in one reply, it just sometimes needs to split them.

Comment (martinpitt) [reply src/rest.js:38]: You can't really guarantee this with a TCP socket, this would require a SEQPACKET one. AFAICS the only reliable way (and best practice everywhere) is to use jsonl. This was literally invented for streaming json messages. I just ran `curl --unix-socket /run/user/1000/podman/podman.sock http://localhost/v1.12/libpod/events` and it looks correct -- this is proper jsonl.

**Review by martinpitt — APPROVED** [review]
OK as incremental improvement, but it's still a hack IMHO. Thanks!

**Review by martinpitt — APPROVED** [review]
Ooh, this looks really nice now - very elegant solution with the `.pop()`! :star2:

**Comment by martinpitt** [comment]
hopefully unrelated [flakes on rhel-9-1](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1035-20220712-073929-e3a49552-rhel-9-1/log.html), retrying
