### PR TITLE
Commit modal improvements and bug fixes

### LINKED ISSUE #818: commit image dialog needs UI attention
141472940-e3e8db06-c815-424d-b7c5-72f8663bef9c

0. Which image is this commit image dialog affecting? It's unclear, as the title is generic.
1. Can OCI vs. Docker format be switched between commits or change from the original image? The radio buttons here imply that. Also, why isn't one selected by default (the current image format type)? Additionally, the case is "OCI" (an initialism) and "Docker" (a proper noun).
2. Can the image name be changed? Or does it have to be changed versus what is currently used?
3. How many of these fields can be prepopulated with the current values?
4. What is the message? Is it a notes/memo field, where the value doesn't matter, but it's freeform text to explain what changed? How long can it be? (Is it a few words, a sentence, paragraph, or more?)
5. What does pausing and variables have to do with "command"? Right now, the UI implies that they're related. They should be separate fields if they're not related.
6. What does pausing do? Does that affect the container, not the image?
7. What does "set container on build variables" mean? Does it set variables that are used by default when a container is created by this image?
8. Are previously existing variables shown in this commit image dialog?

I can help with the UI once I understand the above a bit better.

### PR DESCRIPTION
**Pull request by marusak**
Fixes #818

Screenshot from 2021-11-23 16-48-30

### CODE REVIEW

File: src/ContainerCommitModal.jsx [hunk 1]
```diff
@@ -112,113 +93,73 @@ class ContainerCommitModal extends React.Component {
...
                 <FormGroup fieldId="commit-dialog-image-tag" label={_("Tag")}>
                     <TextInput id="commit-dialog-image-tag"
+                               placeholder="latest" // Do not translate
                                value={this.state.tag}
                                onChange={value => this.handleInputChange("tag", value)} />
                 </FormGroup>
 
                 <FormGroup fieldId="commit-dialog-author" label={_("Author")}>
                     <TextInput id="commit-dialog-author"
+                               placeholder={_("Example, Your Name <yourname@exmaple.com>")}
```
Comment (garrett) [inline src/ContainerCommitModal.jsx:117]:
```suggestion
                               placeholder={_("Example, Your Name <yourname@example.com>")}
```

Comment (garrett) [reply src/ContainerCommitModal.jsx:117]: Typo fix

File: src/ContainerCommitModal.jsx [hunk 2]
```diff
@@ -112,113 +93,73 @@ class ContainerCommitModal extends React.Component {
...
-                    <Checkbox id="commit-dialog-setonbuild" isDisabled={this.state.onbuildDisabled}
-                              isChecked={this.state.setonbuild}
-                              onChange={value => this.handleInputChange("setonbuild", value)}
-                              label={_("Set container on build variables")} />
-                    {this.state.setonbuild && onbuilds}
+                              label={_("Pause container when creating image")} />
+                    <Checkbox id="commit-dialog-docker"
+                              isChecked={this.state.useDocker}
+                              onChange={value => this.handleInputChange("useDocker", value)}
+                              description={_("Docker format is useful when sharing the image with Docker or Mody Engine")}
```
Comment (garrett) [inline src/ContainerCommitModal.jsx:136]:
```suggestion
                              description={_("Docker format is useful when sharing the image with Docker or Moby Engine")}
```

Another typo fix

File: src/ContainerCommitModal.jsx [hunk 3]
```diff
@@ -112,113 +93,73 @@ class ContainerCommitModal extends React.Component {
...
                 </FormGroup>
             </Form>;
 
         return (
             <Modal isOpen
                    showClose={false}
                    position="top" variant="medium"
-                   title={_("Commit image")}
+                   title={_("Commit container")}
+                   description={cockpit.format(_("Create a new image based on the current state of the $0 container."), this.props.container.Names)}
```
Comment (garrett) [inline src/ContainerCommitModal.jsx:146]: Are we able to wrap the container name with a `<strong>` element? Or do descriptions only support text-only?

**Comment by garrett** [comment]
Is the tag without the `:`? What happens when you do `:foo`? Does it tag it with `:foo`, `::foo`, or just fail?

**Comment by marusak** [comment]
> Is the tag without the :? What happens when you do :foo? Does it tag it with :foo, ::foo, or just fail?

> (It's good and fine without :, but it should accept :tagname too as the tagname tag, as some people would be used to typing :, right?)

The tag is without `:`. `:` is just separator, not part of tag itself. If you do `:foo` it will fail. But indeed, we could check for leading `:` and drop it to make it more user friendly.

File: src/ContainerCommitModal.jsx (hunk 3 above)
Comment (martinpitt) [reply src/ContainerCommitModal.jsx:146]: Marius has a clever [fmt_to_fragments()](https://github.com/cockpit-project/cockpit/blob/main/pkg/storaged/utilsx.jsx) helper which can help with translating strings with markup. We could move that to pkg/lib for sure.

**Comment by marusak** [comment]
> Is the tag without the :? What happens when you do :foo? Does it tag it with :foo, ::foo, or just fail?

> (It's good and fine without :, but it should accept :tagname too as the tagname tag, as some people would be used to typing :, right?)

The tag is without `:`. `:` is just separator, not part of tag itself. If you do `:foo` it will fail. But indeed, we could check for leading `:` and drop it to make it more user friendly.

File: src/ContainerCommitModal.jsx [hunk 4]
```diff
@@ -112,113 +93,73 @@ class ContainerCommitModal extends React.Component {
...
+                           helperTextInvalid={this.state.nameError}>
                     <TextInput id="commit-dialog-image-name"
                                value={this.state.imageName}
+                               validated={this.state.nameError ? "error" : "default"}
                                onChange={value => this.handleInputChange("imageName", value)} />
                 </FormGroup>
 
                 <FormGroup fieldId="commit-dialog-image-tag" label={_("Tag")}>
                     <TextInput id="commit-dialog-image-tag"
+                               placeholder="latest" // Do not translate
```
[the remark this answers is not in the document]
Comment (jelly) [reply src/ContainerCommitModal.jsx:110]: Ah, it's the default value, so I think we should just set it as value instead of a placeholder?

**Review by jelly — CHANGES_REQUESTED** [review]

File: src/ContainerCommitModal.jsx (hunk 4 above)
[the remark this answers is not in the document]
Comment (marusak) [reply src/ContainerCommitModal.jsx:110]: @garrett I followed here the design, WDYT?

[the remark this answers is not in the document]
Comment (garrett) [reply src/ContainerCommitModal.jsx:110]: "latest" is not an example; it is what you'd get by default if you don't enter anything.

https://www.patternfly.org/v4/components/form/design-guidelines/#placeholder-text-0

> If your placeholder text demonstrates a correct input, introduce it as an example so that users can distinguish impermanent examples from field labels and their own inputted text.

If we think it looks too inconsistent, then we can drop the latest and add some helper text saying that if no tag is given, then it defaults to "latest".

[the remark this answers is not in the document]
Comment (garrett) [reply src/ContainerCommitModal.jsx:110]: What happens if author is blank?

File: src/ContainerCommitModal.jsx (hunk 3 above)
Comment (marusak) [reply src/ContainerCommitModal.jsx]: Done

File: src/util.js [hunk 5]
```diff
@@ -174,3 +176,17 @@ export function compare_versions(a, b) {
...
+
+    function replace(part) {
+        if (part[0] == "$") {
+            return args[parseInt(part.slice(1))];
+        } else
+            return part;
+    }
+
+    return React.createElement.apply(null, [React.Fragment, { }].concat(fmt.split(/(\$[0-9]+)/g).map(replace)));
+}
```
Comment (jelly) [inline src/util.js:192]: This is already in src/lib with this commit https://github.com/cockpit-project/cockpit-podman/commit/47a97efebdd036b0f45f2a7388beea8dfbaac7cd

**Review by jelly — CHANGES_REQUESTED** [review]

File: src/util.js (hunk 5 above)
Comment (marusak) [reply src/util.js]: Ooops, sorry, fixed

**Review by jelly — APPROVED** [review]
